from datetime import datetime

def report_writer_agent(keyword: str, cves: list, summary: dict) -> dict:
    """
    Agent 3 : Génère un rapport Markdown structuré et prêt à exporter.
    """
    print(f"[Report Writer] Génération du rapport...")

    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Header
    report = f"""# Security Vulnerability Report
**Topic:** {keyword}
**Generated:** {now}
**Total CVEs analyzed:** {cves.__len__()}

---

## Severity Overview

| Severity | Count |
|----------|-------|
| 🔴 CRITICAL | {summary.get('critical_count', 0)} |
| 🟠 HIGH | {summary.get('high_count', 0)} |
| 🟡 MEDIUM | {summary.get('medium_count', 0)} |

---

##  AI Analysis

{summary.get('summary', 'No analysis available.')}

---

## CVE Details

"""
    # Détails de chaque CVE
    for cve in cves:
        severity = str(cve.get('severity', 'N/A')).upper()
        emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🟢"}.get(severity, "⚪")

        report += f"""### {emoji} {cve['id']} — Score: {cve['score']} ({severity})
**Published:** {cve['published']}
**Description:** {cve['description']}
**Reference:** [{cve['url']}]({cve['url']})

---

"""

    # Footer
    report += f"""##  Disclaimer
*This report is AI-generated for informational purposes. Always verify findings manually.*

*Generated by Security Agent System*
"""

    print(f" [Report Writer] Rapport généré ({len(report)} caractères).")

    return {
        "report": report,
        "filename": f"report_{keyword.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M')}.md"
    }